using System.Security.Cryptography;
using System.Text;
using KudibaInvoicing.Domain.Ports;
using KudibaInvoicing.Domain.ValueObjects;

namespace KudibaInvoicing.Infrastructure.Crypto;

public class RsaCryptoSigner : IRsaCryptoSigner, IDisposable
{
    private readonly RSA _rsa;
    private readonly string _keyVersion;
    private bool _disposed;

    public RsaCryptoSigner(string? privateKeyPem = null, string keyVersion = "1")
    {
        _keyVersion = keyVersion;
        _rsa = RSA.Create(2048);

        if (!string.IsNullOrWhiteSpace(privateKeyPem))
        {
            _rsa.ImportFromPem(privateKeyPem);
        }
        else
        {
            // Check environment variable
            var envKey = Environment.GetEnvironmentVariable("AGT_RSA_PRIVATE_KEY_PEM");
            if (!string.IsNullOrWhiteSpace(envKey))
            {
                _rsa.ImportFromPem(envKey);
            }
            // Otherwise, an ephemeral 2048-bit key is generated by RSA.Create(2048)
        }
    }

    public SignedInvoiceResult SignCanonicalBuffer(string canonicalBuffer, string? privateKeyPem = null)
    {
        RSA rsaToUse = _rsa;
        bool ephemeral = false;

        if (!string.IsNullOrWhiteSpace(privateKeyPem))
        {
            rsaToUse = RSA.Create(2048);
            rsaToUse.ImportFromPem(privateKeyPem);
            ephemeral = true;
        }

        byte[] bufferBytes = Encoding.UTF8.GetBytes(canonicalBuffer);
        byte[] hash = SHA256.HashData(bufferBytes);

        try
        {
            byte[] signatureBytes = rsaToUse.SignHash(hash, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
            string signatureBase64 = Convert.ToBase64String(signatureBytes);
            string hashHex = Convert.ToHexStringLower(hash);
            string validationChars = ValidationCode.ExtractFromBase64Signature(signatureBase64);

            return new SignedInvoiceResult(
                signatureBase64,
                hashHex,
                validationChars,
                DateTime.UtcNow
            );
        }
        finally
        {
            CryptographicOperations.ZeroMemory(hash);
            CryptographicOperations.ZeroMemory(bufferBytes);
            if (ephemeral)
            {
                rsaToUse.Dispose();
            }
        }
    }

    public bool VerifySignature(string canonicalBuffer, string signatureBase64, string? publicKeyPem = null)
    {
        RSA rsaToUse = _rsa;
        bool ephemeral = false;

        if (!string.IsNullOrWhiteSpace(publicKeyPem))
        {
            rsaToUse = RSA.Create();
            rsaToUse.ImportFromPem(publicKeyPem);
            ephemeral = true;
        }

        byte[] bufferBytes = Encoding.UTF8.GetBytes(canonicalBuffer);
        byte[] hash = SHA256.HashData(bufferBytes);

        try
        {
            byte[] signatureBytes = Convert.FromBase64String(signatureBase64);
            return rsaToUse.VerifyHash(hash, signatureBytes, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
        }
        catch
        {
            return false;
        }
        finally
        {
            CryptographicOperations.ZeroMemory(hash);
            CryptographicOperations.ZeroMemory(bufferBytes);
            if (ephemeral)
            {
                rsaToUse.Dispose();
            }
        }
    }

    public string GetPublicKeyPem()
    {
        return _rsa.ExportSubjectPublicKeyInfoPem();
    }

    public string GetKeyVersion() => _keyVersion;

    public void Dispose()
    {
        if (!_disposed)
        {
            _rsa.Dispose();
            _disposed = true;
        }
        GC.SuppressFinalize(this);
    }
}
